### ISSUE TITLE
Scroll wheel is reversed

### ISSUE THREAD

**Issue by RenaKunisaki** [dymanoid/Skylines-ModTools#1]
Scrolling up in the ModTools windows causes them to scroll down and vice-versa.

**Comment by dymanoid** [comment]
That's interesting. For me, scrolling works just fine. What device/setting/system do you have?

**Comment by RenaKunisaki** [comment]
Arch Linux AMD64, Logitech MX518. The wheel works fine in the rest of the game and other apps.

**Comment by dymanoid** [comment]
Okay. Will setup a Linux virtual machine and test it. Seems like it's a Mono runtime or Unity issue.

**Comment by dymanoid** [comment]
Yes, looks like this is a known issue: [Unity forum thread](https://forum.unity.com/threads/weird-scrolling-behaviour-with-gui-beginscrollview-since-unity-5-5-3.466347/). Maybe it's already fixed on newer Unity versions, but that won't help us - Cities: Skylines currently uses v5.6.7 and and it doesn't look like the devs want to move on the latest game engine version.

**Comment by dymanoid** [comment]
The issue exists for the old `GUI` subsystem of Unity version 5.x on Linux.
The only solution would be to re-implement the whole GUI using custom drawing (like the game itself), but it's too much work...
